### ISSUE TITLE
Inkdrop crashed after installing plugin.

### ISSUE THREAD

**Issue by CHBrianLiu** [heathyboyj/inkdrop-switch-note#5]
Hi @heathyboyj,

This plugin is what I'm looking for! Unfortunately, the Inkdrop crashed after I installed the switch-note. It can be reproduced by enabling the plugin from preference. There's traceback messages as pasted below.

```
TypeError: _typeof is not a function
    at _possibleConstructorReturn (/Users/chun-hungliu/Library/Application Support/inkdrop/packages/switch-note/node_modules/@babel/runtime/helpers/possibleConstructorReturn.js:6:16)
    at new Dropdown (/Users/chun-hungliu/Library/Application Support/inkdrop/packages/switch-note/node_modules/semantic-ui-react/dist/commonjs/modules/Dropdown/Dropdown.js:141:56)
    at Lg (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/react-dom/cjs/react-dom.production.min.js:134:177)
    at fi (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/react-dom/cjs/react-dom.production.min.js:176:155)
    at Rj (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/react-dom/cjs/react-dom.production.min.js:263:496)
    at Qj (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/react-dom/cjs/react-dom.production.min.js:246:271)
    at Kj (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/react-dom/cjs/react-dom.production.min.js:246:200)
    at yj (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/react-dom/cjs/react-dom.production.min.js:239:178)
    at /Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/react-dom/cjs/react-dom.production.min.js:123:121
    at exports.unstable_runWithPriority (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/scheduler/cjs/scheduler.production.min.js:19:473)
    at cg (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/react-dom/cjs/react-dom.production.min.js:122:331)
    at fg (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/react-dom/cjs/react-dom.production.min.js:123:67)
    at X (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/scheduler/cjs/scheduler.production.min.js:17:190)
    at t (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/scheduler/cjs/scheduler.production.min.js:11:157)
    at __trace__ (/Applications/Inkdrop.app/Contents/Resources/app.asar/app/static/node_modules/@bugsnag/browser/dist/bugsnag.js:2231:34)
```

If any information is needed, I will provide it as soon as possible. Thanks in advance.

**Comment by balance-wtf** [comment]
Same here, this is what I'm getting:
![image](https://user-images.githubusercontent.com/50832180/110675941-bb932f80-81d3-11eb-8f59-1d7e865729c6.png)

**Comment by heathyboyj** [comment]
Apologies, my day-to-day life has me completely swamped at the moment, so I've been unable to keep the package up to date. I'll attempt to look at this as soon as I get a free moment!
